# Site settings
title: Tao Cheng's Research Page
email: tcheng@caltech.edu
description: > # this means to ignore newlines until "baseurl:"
  This is Tao's research page. We will show our recent research results here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tcheng.org" # the base hostname & protocol for your site
twitter_username: Tao94037228
github_username:  esemble

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Research Assistant"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
