title: Deep Energy
description: >-
  In-depth investigation of advanced energy technology — battery science,
  CO₂ electroreduction, fuel cells, and computational chemistry.
permalink: ':title/'
baseurl: ""
url: "https://ensemble-learning.github.io"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Deep Energy # add your name
author-img: b1.png # add your photo
about-author: In-depth investigation of advanced energy technology # add description
social-twitter: Tao94037228 # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: esemble
social-linkedin: tao-cheng-5191331a # add your Linkedin handle
social-email: chengtaoliterature@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
